#!/usr/bin/env node

/**
 * Build Configuration Script
 *
 * This script reads environment variables from .env file
 * and generates public/js/config.js with the configuration.
 *
 * Run this script before starting the application:
 *   node build-config.js
 *
 * Or use npm scripts:
 *   npm run build:config
 *   npm start (runs build:config automatically)
 */

const fs = require('fs');
const path = require('path');

// Load environment variables from .env file (if exists)
// On Vercel, environment variables are already in process.env
try {
    require('dotenv').config();
} catch (error) {
    console.log('ℹ️ No .env file found, using system environment variables');
}

// Validate required environment variables
const requiredVars = ['WEBHOOK_URL', 'LOCATION_ID', 'API_TOKEN'];
const optionalVars = ['AIRTABLE_API_KEY', 'AIRTABLE_BASE_ID', 'AIRTABLE_TABLE_ID', 'XI_API_KEY', 'X_API_KEY'];
const missingVars = requiredVars.filter(varName => !process.env[varName]);

// Supported social media platforms
const supportedPlatforms = [
    'facebook', 'instagram', 'threads', 'gbp', 'linkedin',
    'tiktok', 'youtube', 'pinterest', 'community', 'bluesky'
];

if (missingVars.length > 0) {
    console.error('❌ Error: Missing required environment variables:');
    missingVars.forEach(varName => {
        console.error(`   - ${varName}`);
    });
    console.error('\n💡 For local development: Ensure your .env file contains all required variables.');
    console.error('   For Vercel: Ensure environment variables are set in Vercel dashboard.');
    console.error('   See .env.example for reference.\n');
    process.exit(1);
}

// Check optional variables and warn if missing
const missingOptionalVars = optionalVars.filter(varName => !process.env[varName]);
if (missingOptionalVars.length > 0) {
    console.warn('⚠️ Warning: Some optional features may not work without these environment variables:');
    missingOptionalVars.forEach(varName => {
        console.warn(`   - ${varName}`);
    });
    console.warn('   Thumbnails section will be disabled without Airtable configuration.\n');
}

// Build platform accounts object (only include configured platforms)
const platformAccounts = {};
const analyticsProfileIds = {};

supportedPlatforms.forEach(platform => {
    const envVarName = `${platform.toUpperCase()}_ACCOUNT_ID`;
    const accountId = process.env[envVarName];
    if (accountId && accountId.trim()) {
        platformAccounts[platform] = accountId.trim();
    }

    const analyticsVarName = `${platform.toUpperCase()}_ANALYTICS_ID`;
    const analyticsId = process.env[analyticsVarName];
    if (analyticsId && analyticsId.trim()) {
        analyticsProfileIds[platform] = analyticsId.trim();
    }
});

// Generate the config.js content
const configContent = `/**
 * AUTO-GENERATED CONFIGURATION FILE
 *
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 *
 * This file is automatically generated from your .env file.
 * To update configuration:
 *   1. Edit .env file
 *   2. Run: npm run build:config
 *
 * Generated at: ${new Date().toISOString()}
 */

const CONFIG = {
    webhookUrl: '${process.env.WEBHOOK_URL}',
    locationId: '${process.env.LOCATION_ID}',
    apiToken: '${process.env.API_TOKEN}',
    apiBaseUrl: 'https://services.leadconnectorhq.com',
    airtableApiKey: '${process.env.AIRTABLE_API_KEY || ''}',
    airtableBaseId: '${process.env.AIRTABLE_BASE_ID || 'app9IAddifPb7MZ3V'}',
    airtableTableId: '${process.env.AIRTABLE_TABLE_ID || 'tblOO7PBXrcgeQeog'}',
    xiApiKey: '${process.env.XI_API_KEY || ''}',
    xApiKey: '${process.env.X_API_KEY || ''}',

    // Social media platform accounts (for posting)
    // Only platforms with configured account IDs are included
    platformAccounts: ${JSON.stringify(platformAccounts, null, 8).replace(/\n/g, '\n    ')},

    // Analytics profile IDs (for statistics)
    // Only platforms with configured analytics IDs are included
    analyticsProfileIds: ${JSON.stringify(analyticsProfileIds, null, 8).replace(/\n/g, '\n    ')}
};
`;

// Ensure the public/js directory exists
const outputDir = path.join(__dirname, 'public', 'js');
if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}

// Write the config.js file
const outputPath = path.join(outputDir, 'config.js');
try {
    fs.writeFileSync(outputPath, configContent, 'utf8');
    console.log('✅ Configuration file generated successfully!');
    console.log(`   Location: ${outputPath}`);
    console.log(`   Webhook URL: ${process.env.WEBHOOK_URL}`);
    console.log(`   Location ID: ${process.env.LOCATION_ID}`);
    console.log(`   API Token: ${process.env.API_TOKEN.substring(0, 10)}...`);

    // Show Airtable configuration status
    if (process.env.AIRTABLE_API_KEY) {
        console.log(`   Airtable: Configured ✓`);
    } else {
        console.log(`   Airtable: Not configured (thumbnails disabled)`);
    }

    // Show platform accounts configuration
    const configuredPlatforms = Object.keys(platformAccounts);
    if (configuredPlatforms.length > 0) {
        console.log(`   Platform Accounts: ${configuredPlatforms.join(', ')} ✓`);
    } else {
        console.log(`   Platform Accounts: None configured`);
    }

    // Show analytics configuration
    const configuredAnalytics = Object.keys(analyticsProfileIds);
    if (configuredAnalytics.length > 0) {
        console.log(`   Analytics Profiles: ${configuredAnalytics.join(', ')} ✓`);
    } else {
        console.log(`   Analytics Profiles: None configured`);
    }
} catch (error) {
    console.error('❌ Error writing config file:', error.message);
    process.exit(1);
}
